// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VxTelApi.Data.Context;

namespace VxTelApi.Data.Migrations
{
    [DbContext(typeof(VxTelContext))]
    [Migration("20210426010142_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VxTel.Domain.Entities.CodigoAreaTarifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorPorMinuto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tarifa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2706236-88c6-46cd-b2f7-d4b17ed31733"),
                            CodigoDestino = "016",
                            CodigoOrigem = "011",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 731, DateTimeKind.Local).AddTicks(8926),
                            ValorPorMinuto = 1.9m
                        },
                        new
                        {
                            Id = new Guid("c053d14c-363a-4154-ad0b-7bdc48a1a10f"),
                            CodigoDestino = "011",
                            CodigoOrigem = "016",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 734, DateTimeKind.Local).AddTicks(2057),
                            ValorPorMinuto = 2.9m
                        },
                        new
                        {
                            Id = new Guid("4d6645ef-4a28-424a-ad00-c15143d98be4"),
                            CodigoDestino = "017",
                            CodigoOrigem = "011",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 734, DateTimeKind.Local).AddTicks(2083),
                            ValorPorMinuto = 1.7m
                        },
                        new
                        {
                            Id = new Guid("5ee2dee9-b0f7-4884-ac1b-cdb5536d7b8c"),
                            CodigoDestino = "011",
                            CodigoOrigem = "017",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 734, DateTimeKind.Local).AddTicks(2088),
                            ValorPorMinuto = 2.7m
                        },
                        new
                        {
                            Id = new Guid("0948684a-9976-4d61-943c-910c6dd18119"),
                            CodigoDestino = "018",
                            CodigoOrigem = "011",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 734, DateTimeKind.Local).AddTicks(2091),
                            ValorPorMinuto = 0.9m
                        },
                        new
                        {
                            Id = new Guid("266fffb9-e91d-4175-8fbe-85a57c25bfd9"),
                            CodigoDestino = "011",
                            CodigoOrigem = "018",
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 734, DateTimeKind.Local).AddTicks(2095),
                            ValorPorMinuto = 1.9m
                        });
                });

            modelBuilder.Entity("VxTel.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AcrescimoAlemFranquia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinutosFranquia")
                        .HasColumnType("int");

                    b.Property<string>("NomePlano")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plano");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d087ba13-4a23-4875-90a2-2f1bbb6be14e"),
                            AcrescimoAlemFranquia = 0.1m,
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 736, DateTimeKind.Local).AddTicks(1751),
                            MinutosFranquia = 30,
                            NomePlano = "FaleMais 30"
                        },
                        new
                        {
                            Id = new Guid("f1d612c7-35ed-4fa5-baa6-094976289d44"),
                            AcrescimoAlemFranquia = 0.1m,
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 736, DateTimeKind.Local).AddTicks(1770),
                            MinutosFranquia = 60,
                            NomePlano = "FaleMais 60"
                        },
                        new
                        {
                            Id = new Guid("17d6fbc3-4546-459d-8b30-99a472ffad54"),
                            AcrescimoAlemFranquia = 0.1m,
                            DateCreated = new DateTime(2021, 4, 25, 22, 1, 41, 736, DateTimeKind.Local).AddTicks(1784),
                            MinutosFranquia = 120,
                            NomePlano = "FaleMais 120"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
